### ISSUE TITLE
can it be run in python ?

### ISSUE THREAD

**Issue by munirfarzeen** [Ravi-Garg/Unsupervised_Depth_Estimation#2]
can this train model be run in python?

**Comment by Ravi-Garg** [comment]
Yes you can use pycaffe instead of matcaffe.
All matlab do is remove the mean, transpose matlab arrays in the caffe Batch X g X b X r and resize the input images to correct resolution.

I have not tested it but it should work.

**Comment by munirfarzeen** [comment]
can you explain, how did you convert the disparty into depth, inthe last step. and why did you do it?

**Comment by Ravi-Garg** [comment]
The network is basically learning to estimate disparities from left image to the right which is inversely proportional to depth. Assuming that the whole dataset is created by the same stereo setup you can convert the prediction to depths by 2 simple steps:
(1) resize prediction to the original image resolution (interpolation) call it flowHr
(2) depth = 389.6304 * (width of prediction) / (width of actual KITTI image )/ flowHr.
Thats it.

**Comment by munirfarzeen** [comment]
calulating the sacle, would you use resize image size or or the orginal kitti image.
because you hvae claulated scale of 1. and the size of image is, after applying resize.
would that cause an error.
i have tried it on aonther kitti image, not from the your given images. this depth conversion doesnt work on it. any idea why?

**Comment by munirfarzeen** [comment]
and another question why did you applu eigen mask?
whats its purpose?

**Comment by Ravi-Garg** [comment]
Eigen's mask is used to evaluate the depth estimates only in a cropped region unless you want to reproduce the numbers you don't need any of it.

I am not sure I understand your other question.
Can you share the image used, the estimated disparity and the depth please?
Only then I can comment.

When you say you tried it, did you try my matlab script or the python code you wrote or something else?
Did your code work with the given images?

**Comment by munirfarzeen** [comment]
![5](https://cloud.githubusercontent.com/assets/23066497/22736167/4d6966c6-ee40-11e6-8b24-bde05dce7295.png)
for example this image.
rightnow im using your matlab script.
im trying to match the  depth map value to ground truth. i see its not close.
here is the predicted_depths with matlab script

https://drive.google.com/file/d/0B1jgaafndE7xNGlteDlQNVp5aEE/view?usp=sharing

**Comment by Ravi-Garg** [comment]
I ran this script over your predictions:
 >>imagesc(1./predicted_depths);axis equal;axis off; axis tight; colormap gray;

and visualized inverse depths to be:
![kitti_disp](https://cloud.githubusercontent.com/assets/20716075/22775985/e77cf49a-eefd-11e6-8e3b-a2a7ebc507c0.jpg)

They look correct to me. Your problem is more about how do you evaluate the depths on KITTI using eigens evaluation protocol and more basic stuff like what is depth and what is disparity for which I recommend reading the paper carefully.

For a quick visualization try this: 
>>clamped_depths = predicted_depths;
>>clamped_depths(predicted_depths<0) = 0;
>>clamped_depths(predicted_depths>50) = 50;
>>h = imagesc(clamped_depths);axis equal;axis off; axis tight; colormap gray;
>>saveas(h,'kitti_depth.jpg')
![kitti_depth](https://cloud.githubusercontent.com/assets/20716075/22775981/e21813f4-eefd-11e6-8ae3-7a25c328f9c1.jpg)

Hope this helps.
