### ISSUE TITLE
generate_depth

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [Ravi-Garg/Unsupervised_Depth_Estimation#3]
Hi,Thanks for your great sharing!
I want to generate the depth of kitti ,I have no idea about it even if i have read the development kit provided by the website(http://www.cvlibs.net/datasets/kitti/raw_data.php). could you please share your code about generating the depth iamges?
Thank you！

**Comment by lxp349899201** [comment]
did you have idea about how to generate the depth images? i got focal * Distance = 389.6304 from the `KITTI_vis_test_seq.m` script file , and the Distance in the kitti dataset paper  is 0.54 m, but where is the focal come from? i can`t find it anywhere in the kitti website and kitti dataset paper.
