### ISSUE TITLE
Prediction result recovery

### ISSUE THREAD

**Issue by kspeng** [Ravi-Garg/Unsupervised_Depth_Estimation#7]
Hi,

I downloaded your prediction result mat, but I can not recover it correctly. I got a 142x697 image from predictions in mat. I plot it our but it's quite weird. All the images look like this example:
![test](https://user-images.githubusercontent.com/9488139/54963918-c5a8be80-4f27-11e9-8ea8-8951a5416fd4.png)

Is there anything I have to do before I save the data to png?

**Comment by Ravi-Garg** [comment]
It seems that you need a matrix transpose.
The issue seems to be the row major/column major conventions used in different languages.
