### ISSUE TITLE
where do you get the camera`s focal?

### ISSUE THREAD

**Issue by lxp349899201** [Ravi-Garg/Unsupervised_Depth_Estimation#8]
i see the 'KITTI_vis_test_seq.m' that you offered in the program, you seem to set (focal f * distance B) equals to 389.6304，i know the B is 0.54 meter in the kitti dataset paper, but how/where do you get the camera`s focal f?

**Comment by Ravi-Garg** [comment]
Provided in the kitti dataset. 
Note: KITTI has different focal length and baseline for different sequences but for this implementation I used a single f*B for training and testing. (In principle f*B/depth is predicted).
